spring:
  application:
    name: web-service-demo
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/Projects/Database/h2/web-service-demo
    url: jdbc:h2:tcp://localhost/~/Projects/Database/h2/web-service-demo
    username: sa

mybatis:
  mapper-locations: classpath:/mappers/*.xml
