spring:
  application:
    name: web-service-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Projects/Database/h2/web-service-demo
    username: sa
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-dir: /Users/yeoreum/Projects/file-storage